### ISSUE TITLE
CSS-X-Fire перехал на github

### ISSUE THREAD

**Issue by ranwise** [iliakan/javascript-tutorial-ru#10]
CSS-X-Fire переехал на [github](https://github.com/ronniekk/css-x-fire), обновлений нет почти 3 года, есть [форк годичной давности](https://github.com/zolotov/css-x-fire), возможно уже не работает в новых версиях

https://github.com/iliakan/javascript-tutorial-ru/blame/master/9-tools/1-tools-browser-extensions/article.md#L51

**Comment by iliakan** [comment]
Подредактируй, тогда, пожалуйста, статью, может его удалить, что-то другое полезное написать?

**Comment by ranwise** [comment]
сложно рекомендовать для firefox что-то полезное, так как они внедряют WebExtensions и в ноябрьской 57 версии firefox перестанут работать все плагины без их поддержки, а еще проблема в том что через WebExtensions некоторые функции не возможно реализовать

сейчас вот [3,311](https://addons.mozilla.org/en-US/firefox/tag/firefox57) плагинов с поддержкой firefox 57

из программ можно добавить описание на [Postman](https://www.getpostman.com/) - тестирование и работа с api

**Comment by iliakan** [comment]
неактивно
