### ISSUE TITLE
Flash & Java Applet в Интро статье

### ISSUE THREAD

**Issue by Demetri0** [iliakan/javascript-tutorial-ru#114]
Читал статью [Intro](https://learn.javascript.ru/intro) и в ходе чтения у меня сложилось впечатление, будто автор пытается чресчур сильно превознести достоинство данных технологий, не упоминая о таких недостатках как всеобщий отказ браузеров от поддержки `Flash` и истинного гемороя для пользователя сайта с тем чтобы заставить работать Java апплет в современных баузерах.

Я бы хотел просто услышать ещё чьё-либо мнение по этому поводу, потому как считаю что в данных формулировках у начинающего читателя может сложиться ложное впечатление об этих технологиях.

Кто что думает по этому поводу?

**Comment by iliakan** [comment]
неактивность
