### ISSUE TITLE
FireBug в прошлом

### ISSUE THREAD

**Issue by Demetri0** [iliakan/javascript-tutorial-ru#115]
Статься [DevTools](https://learn.javascript.ru/devtools)

Кажется разработка FireBug прекращена, а весь его основной функционал был вшит в консоль современного FireFox.

**Comment by ranwise** [comment]
уже пора статью обновить полностью

вот [новая статья](https://www.smashingmagazine.com/2017/12/grid-inspector/) про дебаг CSS Grid Layouts в Firefox

**Comment by iliakan** [comment]
Да в англ версии этого нет, бэкпорт.
