### ISSUE TITLE
Три точки, вместо троеточия

### ISSUE THREAD

**Issue by ooPASHAoo** [iliakan/javascript-tutorial-ru#140]
https://learn.javascript.ru/string
В ДЗ "Усечение строки", говориться использовать "три точки", а в тестах проверяется "троеточие", таким образом даже "решение" не проходит "тесты".
Нужно изменить "троеточие" в тестах, на "три точки"
http://plnkr.co/edit/WNlhZdeL7jeeUBRYr7f9?p=preview

**Comment by iliakan** [comment]
Переписать с англ.
