### ISSUE TITLE
Правки текста в статье про eval

### ISSUE THREAD

**Issue by ooPASHAoo** [iliakan/javascript-tutorial-ru#141]
https://learn.javascript.ru/eval
В конце написано "Ещё примеры использования eval вы найдёте далее, в главе Формат JSON, метод toJSON.", но 
1) Я там не нахожу там примеров с eval
2) Она идет не "далее"
---
Предлагаю убрать эту строчку, или возможно поменять ссылку, на какую-то другую главу, которая идет далее и в ней есть примеры с eval.

// P.S. Не умею пользоваться pull-requests, поэтому создаю issues =(

**Comment by iliakan** [comment]
Закрываю, т.к надо переписывать с англ варианта, и там ок.
