### ISSUE TITLE
Дополнение про "стрелочные функции"

### ISSUE THREAD

**Issue by ooPASHAoo** [iliakan/javascript-tutorial-ru#143]
[Отличное дополнение](https://learn.javascript.ru/es-function#comment-3583998442) от пользователя Constantine Sharov к уроку [Функции](https://learn.javascript.ru/es-function)

> Забыли указать, что стрелочками можно записывать вот так:
> 
> `let foo = (bar) => (bar += 100, bar -= 200, bar)`
> 
> в которой return приходится на последнюю запятую.
> 
> С виду кажется глупо, но в коллбеках для различных методов подходит идеально. Например, 
> 
> `arr.reduce((p, c) => (p[c] = c + 10, p), {});`
> 
> вернёт объект, в котором ключи будут называться по именам элементов исходного массива, а равны будут этим элементам + 10. Если записать просто p[c] = c + 10, будет ошибка, так как будет постоянно возвращаться p[c], а не p.
> 
> Хоть это и немного ниндзя, но это гораздо элегантнее, чем фигурные скобки с return, что выйдет на несколько строчек.
> 
> Ну или ещё пример:
> 
>` let findIndex;`
> `if (arr.some((x, i) => (findIndex = i, x < 0))) return arr[findIndex];`
> Если найдётся элемент массива ниже нуля, его индекс запомнится и будет возвращён, так как метод some() один из немногих перебирающих методов массива, имеющий свой "break". В других вариантах (метод find() + findIndex(), или же some() без запоминания индекса) пришлось бы использовать не один цикл, а два.
> 
> Также, в стрелочных однострочных функциях очень удобно объявлять переменные вместе с функцией, например, поиск площади треугольника формулой Херона
> 
> `const heron = (a, b, c, p = (a + b + c) / 2) => Math.sqrt(p * (p - a) * (p - b) * (p - c))`
> 
> вместо
> 
> `const heron = (a, b, c) => {`
>   `let p = (a + b + c) / 2;`
>   `return Math.sqrt(p * (p - a) * (p - b) * (p - c));`
> `}`
> Предполагается, что будет три аргумента (a, b, c). Полупериметр объявляется 4 аргументом и сразу высчитывается. А с защитой от дурака лучше записывать так:
> 
> `const heron = (a, b, c, p) => (p = (a + b + c) / 2, Math.sqrt(p * (p - a) * (p - b) * (p - c)))`

**Comment by iliakan** [comment]
Код должен быть понятен, это самое главное.

С запятой в общем понятно, но не идеально.. И это напрямую не связано с arrow функциями.
Сложная функциия - фиг скобки...
