### ISSUE TITLE
Ошибка в уроке Язык JavaScriptМетоды объектов и контекст вызова

### ISSUE THREAD

**Issue by medinsky** [iliakan/javascript-tutorial-ru#168]
http://learn.javascript.ru/call-apply 

в блоке "Вызов call/apply с null или undefined"

Оба примера "Современный стандарт" и "без use strict" выводят всегда одинаковые значения null в браузере Google Chrome. 

window не выводит.

**Comment by areh-sa** [comment]
Если открыть вариант "без use strict" в песочнице - можно заметить, что "use strict" появился перед кодом функции.
Если удалить эту строчку в коде, то выведет window.

Тут нет ошибки в уроке. Как мне кажется, ошибка в разметке (не установлен атрибут "не строгого режима"), либо в воспроизводящем код скрипте (и открывающем его в песочнице)

**Comment by iliakan** [comment]
Закрываю, т.к надо переписывать с англ варианта, и там ок.
