### ISSUE TITLE
Ошибка в примере урока "Координаты в документе"

### ISSUE THREAD

**Issue by glebkema** [iliakan/javascript-tutorial-ru#177]
Раздел "Получение координат", https://learn.javascript.ru/coordinates-document#getCoords
В коде примера свойства `pageYOffset` и `pageXOffset` оказались сами по себе. Перед ними нужно добавить `window.`.

Сейчас:
```javascript
function getCoords(elem) { // кроме IE8-
  var box = elem.getBoundingClientRect();

  return {
    top: box.top + pageYOffset,
    left: box.left + pageXOffset
  };

}
```
Нужно:
```javascript
function getCoords(elem) { // кроме IE8-
  var box = elem.getBoundingClientRect();

  return {
    top: box.top + window.pageYOffset,
    left: box.left + window.pageXOffset
  };

}
```

**Comment by VladIT4** [comment]
А это же без разницы. Все равно все свойства window копируются в глобальной области.

**Comment by glebkema** [comment]
@VladIT4  Спасибо. Я не прав, закрываю.
