### ISSUE TITLE
Горизонтальная прокрутка в статье о метриках элементов

### ISSUE THREAD

**Issue by mvasin** [iliakan/javascript-tutorial-ru#186]
В статье https://learn.javascript.ru/metrics автор почему-то исходит из того, что горизонтальной полоски прокрутки не существует в принципе:

> На рисунке выше посмотрим вначале на clientHeight, её посчитать проще всего. Прокрутки нет, так что это в точности то, что внутри рамок...

Между тем горизонтальный скроллбар может появиться с тем же успехом, что и вертикальный.

**Comment by iliakan** [comment]
Да, но обычно его избегают, а работают с вертикальным.

Кроме того, горизонтальный скролл по сути работает так же, поэтому достаточно разобраться с вертикальным.
