### ISSUE TITLE
Ошибка в описании ответа на задачу 

### ISSUE THREAD

**Issue by HeleneGritsuk** [iliakan/javascript-tutorial-ru#200]
На странице https://learn.javascript.ru/regexp-groups в задаче "Разобрать выражение"
Есть текст:
Итоговый массив будет включать в себя компоненты:
result[0] == "1.2 + 12" (вначале всегда полное совпадение)
result[1] == "1" (первая скобка)
result[2] == "2" (вторая скобка – дробная часть (\.\d+)?)
result[3] == "+" (…)
result[4] == "12" (…)
result[5] == undefined (последняя скобка, но у второго числа дробная часть отсутствует)

для result[1] и  result[2] неверно указаны совпадения для скобочных групп
![2018-07-14_00-39-55](https://user-images.githubusercontent.com/18267727/42715264-d2085bb4-86fe-11e8-8aab-8295b9b1e558.png)

**Comment by RAYDENFilipp** [comment]
Cоздал [запрос](https://github.com/iliakan/javascript-tutorial-ru/pull/212)
