### ISSUE TITLE
Утверждение некорректно 

### ISSUE THREAD

**Issue by taleh007** [iliakan/javascript-tutorial-ru#243]
В [главе](https://github.com/iliakan/javascript-tutorial-ru/blob/master/1-js/4-data-structures/2-number/article.md) последнее [раздела](https://learn.javascript.ru/number#netochnye-vychisleniya) выглядит не совсем корректно.

`Ради справедливости заметим, что в точности то же самое происходит в любом другом языке, где используется формат IEEE 754, включая Java, C, PHP, Ruby, Perl.`

Причина:

- в процессе изучения материала читатель мог не обратить внимание на немаловажный факт о том, что в JS используется один класс для всех видов чисел.
 
Поэтому следующий код вводит в заблуждения

```javascript 
alert( 9999999999999999 ); // выведет 10000000000000000
```

например в Ruby

```Ruby
puts 9999999999999999 # выведет 9999999999999999
```

В других языках есть различные классы или примитивы для таких чисел ( в JS `BigInt` появился совсем недавно)

**Comment by taleh007** [comment]
@iliakan

**Comment by iliakan** [comment]
Имеется в виду потеря точности для чисел с плавающей точкой.

Вот, к примеру, ruby:
```
irb(main):001:0> 0.1 + 0.2
=> 0.30000000000000004
```
Пришлите, пожалуйста, уточняющий PR?

**Comment by taleh007** [comment]
> Имеется в виду потеря точности для чисел с плавающей точкой.
> 
> Вот, к примеру, ruby:
> 
> ```
> irb(main):001:0> 0.1 + 0.2
> => 0.30000000000000004
> ```
> Пришлите, пожалуйста, уточняющий PR?

Да, все эти ЯП используют IEEE-754 и, соответсвенно, ошибка сохраняется для чисел с плавающей точкой. Однако для людей не знакомых с другими языками складывается впечатление, будто потеря точности сохраняется и на числа целочисленные (в силу того, что в JS есть только один примитив для чисел).

> Ради справедливости заметим, что **в точности то же самое** происходит в любом другом языке, где используется формат IEEE 754

Предлагаю конкретизировать утверждение, чтобы его нельзя было читать отдельно от контекста.

**Comment by iliakan** [comment]
Пришлите, пожалуйста, PR.

**Comment by taleh007** [comment]
Fixed in https://github.com/iliakan/javascript-tutorial-ru/pull/246
