### ISSUE TITLE
Ошибка в Promise.reject(error) 

### ISSUE THREAD

**Issue by micro-chipset** [iliakan/javascript-tutorial-ru#247]
Ошибка в описании Promise.reject(error) 
Аналогично Promise.reject(error) создаёт уже выполнившийся промис, но не с успешным результатом, а с ошибкой error.

Видимо имелось ввиду Аналогично Promise.resolve(value)

https://learn.javascript.ru/promise

**Comment by vvscode** [comment]
да вроде все ок, `Аналогично` тут отсылка на предыдущий пункт

те не `A аналогично B`, а `A. Аналогично B`

**Comment by micro-chipset** [comment]
Хотя да может вы и правы просто недопонял. Promise.reject(error) аналогично Promise.resolve(value) так было бы понятнее
