### ISSUE TITLE
Неправильно сделан пример для задачи

### ISSUE THREAD

**Issue by sergnik1995** [iliakan/javascript-tutorial-ru#258]
https://github.com/iliakan/javascript-tutorial-ru/blob/master/1-js/7-js-misc/3-settimeout-setinterval/8-debounce/task.md тут указано, что первой выполнится f(1) хотя в ответе первой выполняется f(2).

**Comment by vvscode** [comment]
https://github.com/iliakan/javascript-tutorial-ru/pull/259
