### ISSUE TITLE
Как получить список всех URLs (файлов на Github), упорядоченных по разделам?

### ISSUE THREAD

**Issue by w3lifer** [iliakan/javascript-tutorial-ru#267]
Как получить список всех URLs (файлов на Github), упорядоченных по разделам. Например, как на главной странице: https://learn.javascript.ru. Мне это нужно, чтобы сгененировать закладки, как например сделано здесь (см. скрин):  https://github.com/w3lifer/laravel-doc-bookmarks.

**Comment by iliakan** [comment]
Нет у нас такого функционала вроде =)
