### ISSUE TITLE
Горизонтальный скролл

### ISSUE THREAD

**Issue by anttibull** [iliakan/javascript-tutorial-ru#269]
Добрый день. В Chrome на Macbook Pro 13 на страницах уроков появляется горизонтальный скролл - https://prnt.sc/mlxl4j

**Comment by iliakan** [comment]
Проблема исчезла?

**Comment by iliakan** [comment]
Или ты сменил макбук? =)

**Comment by anttibull** [comment]
Проблема исчезла, мак не менял)
