### ISSUE TITLE
Тесты на знание

### ISSUE THREAD

**Issue by chashkovdaniil** [iliakan/javascript-tutorial-ru#279]
Решил пройти тест. Прошел. Все неверные результаты проверил в консоле. 
Встретилась пара тестов, где показало что у меня неверный вариант ответа, а верный: "Выведет ошибку". Я проверил в консоле и у меня не выдало ошибок. Как так?
![Снимок экрана от 2019-03-10 20-56-53](https://user-images.githubusercontent.com/45365913/54087849-4046db00-4379-11e9-9171-b2f6373348af.png)
![Снимок экрана от 2019-03-10 21-01-51](https://user-images.githubusercontent.com/45365913/54087854-45a42580-4379-11e9-8a43-56f6f2c61d49.png)

**Comment by vvscode** [comment]
в node.js нет `alert` - проверяй в консоли браузера

**Comment by iliakan** [comment]
use strict!

**Comment by chashkovdaniil** [comment]
> в node.js нет `alert` - проверяй в консоли браузера

там есть console.log) я его использую вместо алерта
