### ISSUE TITLE
В блоке навигации по уроку раздела "Основные операторы" оператор ++ или -- может быть разорван при отображении

### ISSUE THREAD

**Issue by nexus3a** [iliakan/javascript-tutorial-ru#286]
Пример: ссылка на "Инкремент/декремент: ++, --" может отобразиться как

Инкремент/декремент: ++, -
\-

Второй минус перенесён на другую строку. Требуется сделать "++" и "--" неразрывными (учитывая возможность изменять масштаб шрифта).

То же самое касается ссылки "Сложение строк, бинарный +". Она отображается как

Сложение строк, бинарный 
+

Плюс перенесён на другую строку. Лучше сделать "бинарный +" неразрывным.

**Comment by iliakan** [comment]
Где такое происходит? Попробуйте в код их завернуть `--`

**Comment by nexus3a** [comment]
Добрый день! Во вложении - скриншот с частью страницы https://learn.javascript.ru/operatorsСтрелочками отметил "разорванные" операторы. С уважением,Алексей 19.04.2019, 12:09, "Ilya Kantor" <notifications@github.com>:Где такое происходит? Попробуйте в код их завернуть --—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
