### ISSUE TITLE
Разделы для ES-2016/2017/2018/2019

### ISSUE THREAD

**Issue by oleedd** [iliakan/javascript-tutorial-ru#290]
Стоит добавлять ES разделы для каждого года, тем более следующие релизы после 2015 намного меньше.
Каждый год добавляются интересные возможности.
Стандарт JavaScript развивается, а учебник - нет.

**Comment by iliakan** [comment]
https://github.com/javascript-tutorial/ru.javascript.info

**Comment by oleedd** [comment]
Почему не создаются новые темы на русском? Это же самый лучший учебник, который необходимо развивать.  Перевод на другие языки не так важен, могут и гугл переводчиком воспользоваться. Он уже намного лучше переводит.

**Comment by vvscode** [comment]
Там речь про перевод с английского

**Comment by oleedd** [comment]
Да и португальский уже тоже...
В конце концов можно собирать донат на создание новых тем.

**Comment by oleedd** [comment]
В конце концов можно собирать донат на создание новых тем.
