### ISSUE TITLE
Ошибка в коде на сайте

### ISSUE THREAD

**Issue by UndefindName** [iliakan/javascript-tutorial-ru#291]
https://learn.javascript.ru/function-basics#vozvrat-znacheniya
Код при любых ответах выводит сообщение "Доступ получен"

![unknown](https://user-images.githubusercontent.com/76735226/127569736-f7f7d66a-2e6d-4153-882e-bce7869fc769.png)

![unknown2](https://user-images.githubusercontent.com/76735226/127569733-cc3ca04f-a51d-4c75-82ed-1dc537c3bf37.png)

**Comment by iliakan** [comment]
Nope.
