### ISSUE TITLE
Ваша sort не рефлексивна

### ISSUE THREAD

**Issue by safinaskar** [iliakan/javascript-tutorial-ru#30]
http://learn.javascript.ru/closures-usage . В функцию sort передаётся функция с таким телом: "return a.name > b.name ? 1 : -1". Т. е. она не возвращает ноль на равных аргументах, она не рефлексивна. Так нельзя. ECMA 8.0 говорит, что в такой ситуации результат работы sort неопределён: http://www.ecma-international.org/ecma-262/8.0/index.html#sec-array.prototype.sort . Исправьте это место и все места, где подобное передаётся в sort

**Comment by iliakan** [comment]
Ну и неопределен и что? Встроенная сортировка тоже не стабильна и может поменять равные значения местами.
