### ISSUE TITLE
Неанонимная функция

### ISSUE THREAD

**Issue by safinaskar** [iliakan/javascript-tutorial-ru#31]
На http://learn.javascript.ru/array-methods написано: "Для сортировки объявим и передадим в sort анонимную функцию, которая сравнивает объекты по полю age". Но в приведённом коде эта функция неанонимная

**Comment by RusinovAnton** [comment]
@safinaskar что-то я не могу найти такого предложения на этой странице.

**Comment by safinaskar** [comment]
В решении задачи http://learn.javascript.ru/array-methods#сортировка-объектов . И, кстати, автор уже пофиксил, но не закрыл этот тикет. Так что закрываю
