### ISSUE TITLE
Помогите противостоять хакерам.

### ISSUE THREAD

**Issue by KeyJoo** [iliakan/javascript-tutorial-ru#44]
Приветствую.
Есть проблема: ранее на сайте была форма заявки, так вот с недавнего времени стали приходить явно спамерские письма.

Читая статью [CSRF](https://github.com/iliakan/javascript-tutorial-ru/blob/master/4-ajax/13-csrf/article.md) мне стала понятна теория механизма исполнения запроса (от хакера), а как вот, **как реализовать данный пример** у себя на сайте, пока что нет ясности.

Как сервер генерит ключ? За это отвечает file.js?

**Comment by iliakan** [comment]
Извините, видимо вам в комментарии, но надеюсь вы уже разобрались.
