### ISSUE TITLE
Строки, slice и substr методы

### ISSUE THREAD

**Issue by oceanic71** [iliakan/javascript-tutorial-ru#53]
В статье про строки https://learn.javascript.ru/string
Когда речь идет о различиях между  slice и substring, для substring упоминается что
> Слишком большие значения усекаются до длины строки 

По-моему это предложение лучше вынести в описание самого substring, т.к. оба метода здесь работают одинаково, т.е. 
"hello".slice(0, 100) // hello
"hello".substring(0, 100) // hello

**Comment by iliakan** [comment]
Разная работа с отрицательными значениями.
