### ISSUE TITLE
Проблемы с примером в scope для new Function

### ISSUE THREAD

**Issue by xlazex** [iliakan/javascript-tutorial-ru#55]
[Здесь](https://github.com/iliakan/javascript-tutorial-ru/blob/master/1-js/5-functions-closures/3-scope-new-function/article.md) не работает пример с new Function
```
var a = 1;
function getFunc() {
  var a = 2;
  var func = new Function('', 'alert(a)');
  return func;
}
getFunc()(); // 1, из window
```
Возвращает a undefined! Все проблемы из-за того, что `var a = 1` нет в window!  ( [подробнее](http://disq.us/p/1lyoenw) )

**Comment by iliakan** [comment]
Это если вы неправильно запускаете.

**Comment by iliakan** [comment]
Поправил.
