### ISSUE TITLE
Не работает ссылка

### ISSUE THREAD

**Issue by ranwise** [iliakan/javascript-tutorial-ru#97]
Не работает ссылка на перевод спецификации http://es5.javascript.ru/ (в шапке сайта она тоже не работает)

https://github.com/iliakan/javascript-tutorial-ru/blame/master/1-js/1-getting-started/2-pre-coding/article.md#L47

возможно её можно поменять на http://learn.javascript.ru/es-modern

**Comment by iliakan** [comment]
Убрал, все-таки староват уже перевод тот =)
